-- Newsletter subscriptions storage
create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null default 'active',
  source text not null default 'unknown',
  ip_address text,
  user_agent text,
  subscribed_at timestamptz not null default now(),
  resubscribed_at timestamptz,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep table shape compatible if the table already exists in another environment.
alter table public.newsletter_subscriptions add column if not exists status text not null default 'active';
alter table public.newsletter_subscriptions add column if not exists source text not null default 'unknown';
alter table public.newsletter_subscriptions add column if not exists ip_address text;
alter table public.newsletter_subscriptions add column if not exists user_agent text;
alter table public.newsletter_subscriptions add column if not exists subscribed_at timestamptz not null default now();
alter table public.newsletter_subscriptions add column if not exists resubscribed_at timestamptz;
alter table public.newsletter_subscriptions add column if not exists unsubscribed_at timestamptz;
alter table public.newsletter_subscriptions add column if not exists created_at timestamptz not null default now();
alter table public.newsletter_subscriptions add column if not exists updated_at timestamptz not null default now();

-- Enforce valid status/source values.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'newsletter_subscriptions_status_check'
      and conrelid = 'public.newsletter_subscriptions'::regclass
  ) then
    alter table public.newsletter_subscriptions
      add constraint newsletter_subscriptions_status_check
      check (status in ('active', 'unsubscribed'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'newsletter_subscriptions_source_check'
      and conrelid = 'public.newsletter_subscriptions'::regclass
  ) then
    alter table public.newsletter_subscriptions
      add constraint newsletter_subscriptions_source_check
      check (source in ('footer', 'blog', 'unknown'));
  end if;
end $$;

update public.newsletter_subscriptions
set source = 'unknown'
where source is null;

create unique index if not exists newsletter_subscriptions_email_unique_idx
  on public.newsletter_subscriptions (lower(email));

create index if not exists newsletter_subscriptions_created_at_idx
  on public.newsletter_subscriptions (created_at desc);

create or replace function public.set_newsletter_subscriptions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_newsletter_subscriptions_updated_at on public.newsletter_subscriptions;
create trigger trg_newsletter_subscriptions_updated_at
before update on public.newsletter_subscriptions
for each row
execute function public.set_newsletter_subscriptions_updated_at();

alter table public.newsletter_subscriptions enable row level security;

-- Public website inserts subscriptions via API.
drop policy if exists "anon_insert_newsletter_subscriptions" on public.newsletter_subscriptions;
create policy "anon_insert_newsletter_subscriptions"
  on public.newsletter_subscriptions
  for insert
  to anon
  with check (true);

-- Authenticated admin users can read/update rows from admin dashboard.
drop policy if exists "authenticated_select_newsletter_subscriptions" on public.newsletter_subscriptions;
create policy "authenticated_select_newsletter_subscriptions"
  on public.newsletter_subscriptions
  for select
  to authenticated
  using (true);

drop policy if exists "authenticated_update_newsletter_subscriptions" on public.newsletter_subscriptions;
create policy "authenticated_update_newsletter_subscriptions"
  on public.newsletter_subscriptions
  for update
  to authenticated
  using (true)
  with check (true);
