-- RFQ table for public inquiry submissions
create table if not exists public.rfqs (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text,
  phone text,
  product_interest text,
  message text not null,
  page_url text,
  ip text,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists rfqs_created_at_idx on public.rfqs (created_at desc);

alter table public.rfqs enable row level security;

-- Allow unauthenticated frontend inserts via anon key.
drop policy if exists "anon_insert_rfqs" on public.rfqs;
create policy "anon_insert_rfqs"
  on public.rfqs
  for insert
  to anon
  with check (true);

-- Optional: allow authenticated users to insert too.
drop policy if exists "authenticated_insert_rfqs" on public.rfqs;
create policy "authenticated_insert_rfqs"
  on public.rfqs
  for insert
  to authenticated
  with check (true);
